modLoader = "javafml"
loaderVersion = "*"
license = "$license"
issueTrackerURL = "$issue_tracker_url"

[[mods]]
logoFile="icon.png"
modId = "$mod_id"
version = "$mod_version"
displayName = "$mod_display_name"
authors = '${String.join(", ",authors)}'
credits = '${String.join(", ",contributors)}'
displayURL = "$homepage_url"
description = "$mod_description"

[[mods]]
modId = "iris"
version = "1.8.0+mc${minecraft}"
displayName = "Celeritas Shaders"
description = '''
Stub, to allow mods detecting Iris to function as expected.
'''

[[dependencies.${mod_id}]]
modId = "${forgeid}"
mandatory = true
type="required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"